[package]
name = "alloy-merkle-tree"
description = "Minimal Merkle Tree implementation"
license = "Apache-2.0"
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/rkdud007/alloy-merkle-tree"
keywords = ["merkle", "tree", "merkle-tree"]
categories = ["cryptography", "data-structures", "blockchain"]
exclude = [".github"]
version = "0.4.0"
edition = "2021"

[dependencies]
hashbrown = "0.14.3"
anyhow = "1.0"
alloy-dyn-abi = { version = "0.6.2", default-features = false }
alloy-primitives = { git = "https://github.com/succinctlabs/alloy-core-private.git", default-features = false }
tiny-keccak = { version = "2.0", features = ["keccak"] }

[patch.crates-io]
tiny-keccak = { git = "https://github.com/succinctlabs/tiny-keccak-private.git", branch = "chris/test" }
